package com.alphapulse.events;

/**
 * A functional interface for listeners that want to receive alpha signal events.
 */
@FunctionalInterface
public interface AlphaSignalListener {
    /**
     * Called when a new alpha signal is generated by the AlphaEngine.
     *
     * @param event The event containing the signal data.
     */
    void onAlphaSignal(AlphaSignalEvent event);
}
